/// <reference types="../CTAutocomplete" />
/// <reference lib="es2015" />
// Generated by CT-Pack
const Desktop = Java.type("java.awt.Desktop");
const URI = Java.type("java.net.URI");

register("command",(...args) => {
    let command = args.join(" ");
    let url = `https://wiki.hypixel.net/index.php?search=${encodeURIComponent(command)}`;
    Desktop.getDesktop().browse(new URI(url));
}).setName("searchwiki").setAliases(['sw', 'wikisearch']);
register("command", (...args) => {
    let command = args.join("_");
    let url = `https://wiki.hypixel.net/${encodeURIComponent(command)}`;
    Desktop.getDesktop().browse(new URI(url));
}).setName("openwiki").setAliases(['ow', 'wikiopen']);
