
[frag_bots]
	frag_bot_2 = ""
	frag_bot_1 = ""
	frag_bot_3 = ""

[custom_commands]
	custom_command_5 = ""
	custom_command_4 = ""
	custom_command_3 = ""
	custom_command_2 = ""
	client_side_1 = false
	client_side_2 = false
	client_side_3 = false
	client_side_4 = false
	client_side_5 = false
	custom_command_1 = ""

