
[general]

	[general.category]
		toggle2 = true
		toggle = true
		text = ""

[module_settings]

	[module_settings.settings]
		ah_escrow = true
		bin_reopen = true

	[module_settings.category]
		toggle2 = true
		toggle = true

